num1 = float(input("Didite o primeiro numero"))
num2 = float (input("Digite o segundo numero"))
soma = (num1 + num2)
print (f"A soma é {soma}")
mult = (num1*num2)
print (f"A mult e {mult}")
div= (num1/num2)
print (f"A divisao é {div}")